### ISSUE TITLE
Vintage camera 

### ISSUE THREAD

**Issue by sampageAUS** [mattbierner/mattbierner.github.io#10]
Hey Matt I recently inherited a vintage monolta and a big box of len's/accessories including and old soligor macro lens, just wondering if you could help me shed some light on how much this stuff is worth as I'm looking too sell it all too pursue my phographing career and I don't want too get ripped off lol any help would be much appreciated, thanks Sam ☺️✌🏼

**Comment by mattbierner** [comment]
Check out what similar items are selling for (and not just listed for) on site like eBay or photo forums to get some idea of what's reasonable. Look at the listing to understand the conditions of the item for sale and how this compares to your copy. After getting the know the market a little, you can then try selling the gear yourself piece by piece, or selling it to a reseller in bulk. Depending on what you have, you may want to sell the more expensive items individually and bundle the rest into a "grab bag".

My advice though: keep some of the old lenses, especially if they are not worth very much. While vintage camera accessories and flash units are generally pretty worthless nowadays, you can still adapt almost any old lens to a modern camera system and shoot with it just fine. Even cheap old lenses can be fun to shoot with and produce some really interesting effects.

Hope that helps. If you want any more specific advice, I'd be happy to help out.
