### ISSUE TITLE
Do you happen to know how to build McCarthy's `amb` operator out of delimited continuations?

### ISSUE THREAD

**Issue by akkartik** [mattbierner/mattbierner.github.io#12]
Since [you seem to have some experience with delimited continuations](https://blog.mattbierner.com/the-delimited-continuation-monad-in-javascript), I thought I'd check. I've been struggling for a while since [this post](http://akkartik.name/coroutines-in-mu), but without making progress. Comments and criticisms also appreciated on my attempt to support delimited continuations in a statement-oriented language.

**Comment by mattbierner** [comment]
Very cool work! 

I’m afraid that you know much more about the area than I do so I probably can’t be of much help. For `amb`, my thought is that you need an outer `reset` and then the `amb` operator itself is a `shift`  that calls the continuation with each possible value. That would sort-of match how I see it implemented using `call/cc`

What specific problems you are running into for your language?

**Comment by akkartik** [comment]
Yeah, I think I understand how to implement it with `call/cc`. [Rosetta Code](https://rosettacode.org/wiki/Amb) has several examples of that. The extra complexity with delimiting the continuations is deciding where to stop. Where to insert the `reset` or potentially multiple `reset`s.

For starters, it seems we need to modify the problem to support delimited continuations. Assuming we have just two calls to `amb`, the original problem assumes a calling trace something like this:

```
...A...
...amb...  // 1
...B...
...amb...  // 2
...C...
```
`C` contains some number of constraints that may restart the computation at either of the two calls to `amb`.

For delimited continuations we need to wrap the operations in an enclosing `reset`. So the calling code is now structured to require at least one 'outer' `reset`:

```
(reset
  ...A...
  ...amb...  // 1
  ...B...
  ...amb...  // 2
  ...C1...
)
...C2...
```

(I don't know yet if the continuation gets called in C1 (inside `reset`) or C2 (outside), so I'm leaving both options open.)

The one constraint I feel is required for the spirit of the problem is: once the continuation or system of continuations is set up, to trigger the entire computation with a single call. If we need to perform multiple calls we're just building an interpreter, and a lot of the 'magic' of `amb` is lost.

Each call to `amb` can be a generator expression, and I know how to build those. But if I make them independent generator expressions, with their own internal `reset`s, then continuing the first won't rerun the arbitrary other computations in `B`. And if each generator expression captures a continuation until the outer `reset`, then I think the continuation would need to be called over and over again. Even if we tried to get around this by somehow performing other calls of the continuation *inside* the block, we'd still end up performing the computations after such an inner call multiple times, which seems undesirable since those computations can be arbitrary.

I'm afraid I'm not being clear. It seems it's hard to describe why one *can't* do something :)

**Comment by difranco** [comment]
As usual, Oleg Kiselyov has the answer.

http://okmij.org/ftp/ML/index.html#amb

**Comment by akkartik** [comment]
I *have* seen that, but I don't remember if I had an issue with it. Maybe it just dropped off my radar. Thanks!
