### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by yzhang-gh** [mattbierner/mattbierner.github.io#16]
I knew you from the VSCode team long ago and felt you are an interesting person. Then I found your blog. Well, I don't know how to define what an interesting person is, but definitely you are.

You have changed my views of many things. I like your projects, although many of them do look kind of "absurd" to me, I just really like them.

Thanks a lot for sharing your experiences.

Just to let you know you have one more audience, although you don't ever need many.

_from your post - Five Years_

**Comment by mattbierner** [comment]
Thank you
