### ISSUE TITLE
Re: Five Years

### ISSUE THREAD

**Issue by Wehrdo** [mattbierner/mattbierner.github.io#17]
I discovered your blog several weeks ago, and just wanted to let you know that I think your work is brilliant. So, don't worry if it seems like nobody is watching, or that people don't see your projects as they ought to be seen, because, like you wrote,
> If the world doesn’t appreciate erotic Theremin videos, it’s the world who’s wrong.

Here's to another five years of exploration.

**Comment by mattbierner** [comment]
Thank you
