### ISSUE TITLE
Printed DNA recycling

### ISSUE THREAD

**Issue by cpitclaudel** [mattbierner/mattbierner.github.io#19]
There is a handwritten sign saying 'no plastic bags' on the commingled recycling trash receptacle in your [picture](https://blog.mattbierner.com/content/2019-04-03-dna-print-conclusion/recycled.jpg); did you remove the paper from the bags before recycling it? (Background: https://www.huffpost.com/entry/how-to-recycle-plastic-bags_n_5c4b80f8e4b0e1872d43b9a4)

**Comment by mattbierner** [comment]
I believe this is about plastic grocery-style bags, not the bags used to hold the recycling

**Comment by cpitclaudel** [comment]
I think Seattle does accept grocery-style bags, as long as they are collected into a large sealed bag, but I can't find anything about bagging recycling beyond https://www.reddit.com/r/SeattleWA/comments/5ny5go/does_seattle_recycle_allow_these_clear_blue_bags/, which doesn't look too reliable.
