### ISSUE TITLE
N3599 won't be coming to C++17

### ISSUE THREAD

**Issue by AndrewPaxie** [mattbierner/mattbierner.github.io#2]
Hi Matt

You wrote

> the lack of raw string user defined literals in C++14 is a pretty
> big inconsistency that I hope C++1z will resolve (see N3599).

in

Matt Bierner, "Pride and Parser Combinators, Part One," 7 February 2016
Available: http://blog.mattbierner.com/stupid-template-tricks-pride-and-parser-combinators-part-one/
Accessed: 18 September 2016

Your hopes to have N3599 in C++17 are dashed: it didn't make it to the Committee Draft (n4606.pdf).

See: "N3599 for C++17," 5 July 2015.
Available: https://groups.google.com/a/isocpp.org/forum/#!topic/std-proposals/YtIPoZ4ESMI
Accessed: 18 September 2016

C++ Standard Evolution Active Issues List (Revision R10)
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4325.html
Accessed: 18 September 2016

This shows Issue 139,

> Discussed in Urbana. The design was approved by EWG, and the author was encouraged 
> to proceed to LEWG and CWG.

It appears to have stayed in this state since then.
### Other proposals

Alternate proposals have appeared from these authors

Andrew Tomazos, "Compile-Time String: std::string_literal<n>," N4121, 4 July 2014.
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4121.pdf
Accessed: 18 September 2016

Michael Price, "A compile-time string library template with UDL operator templates," N4236, 10 October 2010.
Available: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4236.html
Accessed: 18 September 2016

Also, both authors have proposed P0259R0, which revises N4121 and N4236:

Michael Price and Andrew Tomazos, "fixed_string: a compile­time string," P0239R0, 12 February 2016.
Available: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0259r0.pdf
Accessed: 18 September 2016

It gets better.  Louis Dionne has also revised N3599,

Loius Dionne, "Reconsidering literal operator templates for strings," P0424R0, 15 August 2016.
Available: https://github.com/ldionne/wg21/blob/master/generated/P0424R0.pdf
Accessed: 18 September 2016

His argument for the proposal is here:

Louis Dionne, "[P0424] Reconsidering literal operator templates for strings," 15 August 2016.
Available: https://groups.google.com/a/isocpp.org/forum/#!msg/std-proposals/b1X597zMx9s/8RbuYYo6EgAJ
Accessed: 18 September 2016

Dionne is targetting C++20 with this proposal.
### Macro-based workaround in the meantime

If the literal operator template for strings is not implemented in
the compiler then Dionne suggests this workaround macro:

``` cpp
// From P0259R0, adapted to type stream.
//
// Loius Dionne, "Reconsidering literal operator templates for strings,"
// P0424R0, 15 August 2016.
// Available: https://github.com/ldionne/wg21/blob/master/generated/P0424R0.pdf
// Accessed: 18 September 2016

template <std::size_t... N, typename Literal>
stream<Literal::Get(N)...> make_stream(std::index_sequence<N...>, Literal)
{
    return {};
}

#define MAKE_STREAM(LITERAL)                                \
    make_stream(                                            \
        std::make_index_sequence<sizeof(LITERAL) - 1>{},    \
        [] {                                                \
            struct Literal                                  \
            {                                               \
                static constexpr char Get(std::size_t i)    \
                {                                           \
                    return LITERAL[i];                      \
                }                                           \
            };                                              \
            return Literal{};                               \
        }())                                                \
    /**/
```

Example of use:

``` cpp
template <char... chars, typename... Args>
void my_printf(stream<chars...>, Args&&... args) { ... }

my_printf(MAKE_STREAM("int=%d"), 5);
```

**Comment by mattbierner** [comment]
Thanks for the update here.

Sad to see that this was not picked up, as it is actually a very useful feature with many application beyond the sometimes more silly applications I write about. It's good to see that there is still momentum in this area though, and I may see if there's a way to contribute to these proposals. I'm more a fan of the simple approach N3599 offered, but can also see where a more complete compile time string solution may be desirable.

Dionne's macro is an interesting work around too. I certainly hadn't thought of using a lambda like that to create an inline struct. Very clever.

**Comment by AndrewPaxie** [comment]
Yes, indeed.  The invocation of the `Get()` static member function in the pack expansion for the return type was just what I needed in another context.  It was an 'aha' moment for me.

In the meantime, keep up the "stupid template tricks" and I look forward to Halloween 2016 ... .
