### ISSUE TITLE
Please re-review one bug report issue in VSC

### ISSUE THREAD

**Issue by Vigilans** [mattbierner/mattbierner.github.io#20]
It's been days since you said `Let me know if I have misunderstood the problem` and I clarified it's a bug instead of as-designed.

Now, I've reorganized the issue content to make it easier to read, might you please re-review this issue?

https://github.com/Microsoft/vscode/issues/71608

At first, I cautiously query whether it is an designed behavior, but after I debug VSC locally and refer to your explanation, I can make sure it is a bug now.

**Comment by mattbierner** [comment]
Please do not open VS Code issues here
