### ISSUE TITLE
Thank you in the first place, it’s brilliant writing

### ISSUE THREAD

**Issue by am-kantox** [mattbierner/mattbierner.github.io#25]
In regard to this: https://blog.mattbierner.com/10-years-stack-overflow-learnings/

> the only way you can reward them is clicking a little up vote arrow

That is honestly not 102% true. When I see the outstanding answer, I always use the bounty to reward. It’s not anonymous any since 2018 (or even 2017) there is an explicit way to denote “treat this bounty as thank you.”

Regarding everything else in the article—well, I could not agree more. Thank you for writing this.

**Comment by mattbierner** [comment]
Thanks!

Good point about bounties. I always forget that you can award them on other people's questions too
