### ISSUE TITLE
Language Server Protocol

### ISSUE THREAD

**Issue by afonsojramos** [mattbierner/mattbierner.github.io#32]
Hey Matt, 

I'm developing a VSCode tool using the Language Server Protocol and I think could use your help with a few things. In this specific case, I wanted to use the createTextEditorDecorationType, however, using the LSP, which obviously does not allow me to use such function in the server, which means it must have to be executed in the Client, which raises the question, how do I do it? Is there a way I can execute Client functions from the server?

Furthermore, what is the best documentation to follow for all the LSP implementations?

Thanks in advance,
Afonso

**Comment by mattbierner** [comment]
I don't offer personalized VS Code help. If you have a question, please post it on StackOverflow
