### ISSUE TITLE
"Watar" is really cool

### ISSUE THREAD

**Issue by LH-Liu** [mattbierner/mattbierner.github.io#39]
Hello:
         I downloaded and experienced the "watar" app. The effect is really great. I'm very curious. Which technology is used to realize this application? Is it Apple's arkit? Or the algorithm implemented by ourselves?

**Comment by mattbierner** [comment]
It uses ARKit. The basic approach is described here: https://blog.mattbierner.com/reality-shaders/

The complicated part for this app is the water effect. The waves are faked but the raindrops and touches use a basic fluid simulation

**Comment by LH-Liu** [comment]
Oh, thank you very much for your timely reply and answer. I have benefited a lot.
