### ISSUE TITLE
A question about vscode webview implementation

### ISSUE THREAD

**Issue by AkiSakurai** [mattbierner/mattbierner.github.io#48]
https://blog.mattbierner.com/vscode-webview-web-learnings/

Currently local resources are served from origin [...].vscode-resource.vscode-webview.net through service worker on  [uuid].vscode-webview.net.

Since they are different origin, the service worker wont capture the request from iframe inside webview with local resources as src.

May I ask why the local resources is served with different origin?

**Comment by mattbierner** [comment]
It's not actually necessary and we now use a hardcoded resource origin in VS Code:

https://github.com/microsoft/vscode/blob/165611d073e49841c281f246260381f8ac1b2f54/src/vs/workbench/api/common/shared/webview.ts#L26

We previously did this because we needed to transmit the unique id of the webview to the resource loading logic in desktop VS Code where we used electron protocols: https://www.electronjs.org/docs/latest/api/protocol/ However this is not required on web. Once we migrated to use service workers on desktop, I switched us to use a hardcoded resource origin

**Comment by AkiSakurai** [comment]
Thank you for you reply.

I think there is a little misunderstand about my question.

I can see the that resources is loaded with hardcoded origin.
https://vscode-test-web+mount.vscode-resource.vscode-webview.net/

However the active-frame is located under another origin. 
https://6c5f26ca-1543-40f5-8ca6-eb6632bb596d.vscode-webview.net/insider/bedf867b5b02c1c800fbaf4d6ce09cefbafa1592/out/vs/workbench/contrib/webview/browser/pre/fake.html?id=5c9adcdd-183a-4fee-9609-4faa162fabf5

If I put a iframe inside the active-frame, and set the src to local resource, it wont load.
The service worker from 6c5f26ca-1543-40f5-8ca6-eb6632bb596d.vscode-webview.net is unable to see the navigate request from iframe with another origin vscode-test-web+mount.vscode-resource.vscode-webview.net
```
<iframe src="https://file%2B.vscode-resource.vscode-webview.net/worksapceIiframe.html">
</iframe>
```

Cant we reuse the origin of webview endpoint as resource origin?

**Comment by mattbierner** [comment]
The iframe `src` request doesn't go through the service worker of the host page. I forget if this is a implementation bug or an intentional limitation of service workers

**Comment by AkiSakurai** [comment]
The iframe ```src``` request behaves like opening a new tab with ```src``` url.

A service worker has to be registered on origin of ```src``` so that service worker can capture the ```src``` request.

However there is no service worker registered on  ```vscode-test-web+mount.vscode-resource.vscode-webview.net```.

The service worker in vscode is registered on ```6c5f26ca-1543-40f5-8ca6-eb6632bb596d.vscode-webview.net```.

I am suggesting that we can put the local resources under ```
6c5f26ca-1543-40f5-8ca6-eb6632bb596d.vscode-webview.net
``` instead of  ```vscode-test-web+mount.vscode-resource.vscode-webview.net```  so that the service worker can capture iframe ```src``` request.
