### ISSUE TITLE
Creative Commons confusion 

### ISSUE THREAD

**Issue by EmilyClaire** [mattbierner/mattbierner.github.io#5]
I would like to use the bacteria culture picture from the 2015 keyboard article.  I want to put a monocle and a mustache on it for my school fermentation club.  I'm not exactly sure what attribution I need. 

I read the link and see that is share,  attribution,  non commercial.  I'm just new to this. 

Thank you

**Comment by mattbierner** [comment]
Mustaches and monocles are always fine with me

For attribution, if the work is online, include a link to the post. If printed, just include an attribution blurb somewhere indicating where you got the photo from. The attributions can be super small and unobtrusive. The [CC license site](https://creativecommons.org/licenses/by-nc/4.0/) has more details, but I really don't care as long as you are not selling the stuff or using in commercial advertising.

Hope that clears things up.
