### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by NnamdiJr** [mattbierner/mattbierner.github.io#6]
Hey Matt!

My name is Nnamdi and I came across your blog while poking around the webs for interesting projects using UrbanDictionary data.

I'm an aspiring Data Scientist, currently in a Data Science Immersive program at Galvanize in SF. For my capstone project I'm investigating rap & hip-hop lyrics from Genius.com with slang from UrbanDictionary.

I just wanted to drop you a message to say thanks, since your UrbanDictionary word list repo is awesome (and so is your other related work). Saved me a lot of trouble!!

Thank you!

**Comment by mattbierner** [comment]
Thanks. Glad you found the data useful.

It sounds like a fun project idea and I'd be interested to see what you end up finding in these data sets.

Best of luck
