### ISSUE TITLE
 [stylus] Add Stylus language support

### ISSUE THREAD

**Issue by Woogyloaf** [mattbierner/mattbierner.github.io#7]
Any information about Stylus language support in Visual Studio Code ?

**Comment by mattbierner** [comment]
This is my personal blog. Please post VS Code issues / feature requests to the VS Code repo. Stylus support is something an extension would be able to provide

**Comment by Woogyloaf** [comment]
i asking coz of this https://github.com/Microsoft/vscode/issues/113
