### ISSUE TITLE
SICK!!!

### ISSUE THREAD

**Issue by ghost** [mattbierner/mattbierner.github.io#8]
Your a sick person and should be ashamed of what you wrote about OUR PRESIDENT! What happen to respect and common decency and patriotism in this country? grow up and get over it. You lost. You offend President Trump and the million of Americans like me who want him to succeed. I've seen silly stuff on the internet but this is just DISGUSTING. you are thr reason WE voted this way!!

Maybe now you should finally apologize and delete your site since you obviously don't respond to emails.

**Comment by mattbierner** [comment]
http://blog.mattbierner.com/a-how-and-why-of-the-don-and-i/

❤️
